-- AlterTable: DietType
ALTER TABLE "diet_types" ADD COLUMN IF NOT EXISTS "category" TEXT NOT NULL DEFAULT 'restriction',
ADD COLUMN IF NOT EXISTS "macros" JSONB NOT NULL DEFAULT '{}';

-- AlterTable: User
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "activityLevel" DOUBLE PRECISION NOT NULL DEFAULT 1.2,
ADD COLUMN IF NOT EXISTS "age" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS "goal" TEXT NOT NULL DEFAULT 'maintain',
ADD COLUMN IF NOT EXISTS "selectedDietTypeCode" TEXT;
